# Generated by Django 5.0.6 on 2024-05-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has verified their email address.', verbose_name='email verified'),
        ),
    ]
